/**
 * Seed script to create test reports in the database.
 * Usage: node scripts/seedReports.js
 */
require('dotenv').config();
const mongoose = require('mongoose');
const Report = require('../models/Report');
const User = require('../models/User');
const Listing = require('../models/Listing');

async function seed() {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('✅ Connected to MongoDB');

        // Grab a few real users and listings from the DB
        const users = await User.find().limit(5).lean();
        const listings = await Listing.find().limit(5).lean();

        if (users.length < 2) {
            console.error('❌ Need at least 2 users in the database to create reports.');
            process.exit(1);
        }

        console.log(`Found ${users.length} users and ${listings.length} listings`);

        const reporter = users[0]; // First user is the reporter
        const targetUsers = users.slice(1); // Rest are targets

        const reasons = ['spam', 'inappropriate', 'fraud', 'harassment', 'prohibited_item', 'wrong_category', 'duplicate', 'other'];
        const statuses = ['pending', 'pending', 'pending', 'reviewed', 'resolved']; // Weighted toward pending
        const actions = ['none', 'warning', 'content_removed', 'user_banned'];

        const reportsToInsert = [];

        // Create user reports
        for (let i = 0; i < targetUsers.length; i++) {
            const target = targetUsers[i];
            reportsToInsert.push({
                reporter: reporter._id,
                targetType: 'user',
                targetId: target._id,
                targetModel: 'User',
                reason: reasons[i % reasons.length],
                description: `Test report #${i + 1}: This user has been ${reasons[i % reasons.length]}. Generated by seed script.`,
                status: statuses[i % statuses.length],
                ...(statuses[i % statuses.length] === 'resolved' && {
                    reviewedBy: reporter._id,
                    reviewedAt: new Date(),
                    resolution: 'Issue was investigated and resolved.',
                    actionTaken: actions[i % actions.length],
                }),
                ...(statuses[i % statuses.length] === 'reviewed' && {
                    reviewedBy: reporter._id,
                    reviewedAt: new Date(),
                    actionTaken: 'none',
                }),
            });
        }

        // Create listing reports
        for (let i = 0; i < listings.length; i++) {
            const listing = listings[i];
            // Use a different reporter if possible to avoid unique constraint
            const listingReporter = users[Math.min(i + 1, users.length - 1)];
            reportsToInsert.push({
                reporter: listingReporter._id,
                targetType: 'listing',
                targetId: listing._id,
                targetModel: 'Listing',
                reason: reasons[(i + 3) % reasons.length],
                description: `Test listing report #${i + 1}: This listing appears to be ${reasons[(i + 3) % reasons.length]}. Generated by seed script.`,
                status: statuses[i % statuses.length],
                ...(statuses[i % statuses.length] === 'resolved' && {
                    reviewedBy: reporter._id,
                    reviewedAt: new Date(),
                    resolution: 'Listing was reviewed and action was taken.',
                    actionTaken: actions[(i + 1) % actions.length],
                }),
                ...(statuses[i % statuses.length] === 'reviewed' && {
                    reviewedBy: reporter._id,
                    reviewedAt: new Date(),
                    actionTaken: 'warning',
                }),
            });
        }

        // Insert reports (skip duplicates gracefully)
        let inserted = 0;
        for (const report of reportsToInsert) {
            try {
                await Report.create(report);
                inserted++;
            } catch (err) {
                if (err.code === 11000) {
                    console.log(`⏭️  Skipped duplicate: ${report.targetType} ${report.targetId}`);
                } else {
                    console.error(`❌ Error inserting report:`, err.message);
                }
            }
        }

        console.log(`\n🎉 Seeded ${inserted} reports successfully!`);

        // Print summary
        const counts = await Report.aggregate([
            { $group: { _id: '$status', count: { $sum: 1 } } },
        ]);
        console.log('\n📊 Report counts by status:');
        counts.forEach((c) => console.log(`   ${c._id}: ${c.count}`));

    } catch (err) {
        console.error('❌ Seed failed:', err);
    } finally {
        await mongoose.disconnect();
        console.log('\n🔌 Disconnected from MongoDB');
    }
}

seed();
